const TestData = [
  {
    id: 1,
    province: "서울특별시",
    city: "서울",
    created_date: "2023-09-25",
    gender: "남성",
    birth_year: "1990.12.02",
    profile_picture: "사진 링크 1",
    nickname: "JohnDoe",
    registration_date: "2023-09-25",
    content: "안녕하세요! 나는 JohnDoe입니다.",
    gps: 0,
  },
  {
    id: 2,
    province: "경기도",
    city: "용인",
    created_date: "2023-09-24",
    gender: "여성",
    birth_year: "1990.12.02",
    profile_picture: "사진 링크 2",
    nickname: "JaneSmith",
    registration_date: "2023-09-24",
    content: "여행을 좋아하는 JaneSmith입니다.",
    gps: 1,
  },
  {
    id: 3,
    province: "부산광역시",
    city: "부산",
    created_date: "2023-09-23",
    gender: "남성",
    birth_year: "1990.12.02",
    profile_picture: "사진 링크 3",
    nickname: "BobJohnson",
    registration_date: "2023-09-23",
    content: "안녕하세요, BobJohnson입니다.",
    gps: 0,
  },
  {
    id: 4,
    province: "서울특별시",
    city: "서울",
    created_date: "2023-09-25",
    gender: "여성",
    birth_year: "1990.12.02",
    profile_picture: "사진 링크 4",
    nickname: "AliceBrown",
    registration_date: "2023-09-25",
    content: "여행을 떠나고 싶은 AliceBrown입니다.",
    gps: 1,
  },
  {
    id: 5,
    province: "경기도",
    city: "용인",
    created_date: "2023-09-24",
    gender: "남성",
    birth_year: "1990.12.02",
    profile_picture: "사진 링크 5",
    nickname: "EvaWhite",
    registration_date: "2023-09-24",
    content: "함께 여행을 떠날 친구를 찾고 있어요.",
    gps: 0,
  },
  {
    id: 6,
    province: "부산광역시",
    city: "부산",
    created_date: "2023-09-23",
    gender: "여성",
    birth_year: "1990.12.02",
    profile_picture: "사진 링크 6",
    nickname: "ChrisLee",
    registration_date: "2023-09-23",
    content: "안녕하세요, ChrisLee입니다.",
    gps: 1,
  },
  {
    id: 7,
    province: "서울특별시",
    city: "서울",
    created_date: "2023-09-25",
    gender: "남성",
    birth_year: "1990.12.02",
    profile_picture: "사진 링크 7",
    nickname: "GracePark",
    registration_date: "2023-09-25",
    content: "함께 여행을 떠날 친구를 찾고 있어요.",
    gps: 0,
  },
  {
    id: 8,
    province: "경기도",
    city: "용인",
    created_date: "2023-09-24",
    gender: "여성",
    birth_year: "1990.12.02",
    profile_picture: "사진 링크 8",
    nickname: "MikeKim",
    registration_date: "2023-09-24",
    content: "MikeKim입니다. 새로운 친구를 만나고 싶어요!",
    gps: 1,
  },
];

export default TestData;
